# Generated by Django 2.0.5 on 2018-05-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorePDF', models.FileField(upload_to='router_specifications')),
                ('scoreMEI', models.FileField(upload_to='router_specifications')),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
