# Generated by Django 2.0.5 on 2018-05-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20180503_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='scoreMEI',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='scores',
            name='scorePDF',
            field=models.FileField(upload_to=''),
        ),
    ]
