# Generated by Django 2.0.5 on 2018-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20180503_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='composer',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scores',
            name='scoreMEI',
            field=models.FileField(upload_to='router_specifications'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='scorePDF',
            field=models.FileField(upload_to='router_specifications'),
        ),
    ]
