# Generated by Django 2.0.5 on 2018-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20180503_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='composer',
            field=models.CharField(max_length=200),
        ),
    ]
