# Generated by Django 2.0.5 on 2018-05-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20180503_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='scoreMEI',
            field=models.FileField(upload_to='scores/static/scores'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='scorePDF',
            field=models.FileField(upload_to='scores/static/scores'),
        ),
    ]
